using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using Core.Manager;

namespace Core.UI
{
    public class GuildDataUI : MonoBehaviour
    {
        public Text guildName;
        public Text guildRank;
        public Text guildVisitAdventure;
        public Text guildCompleteQuest;
        public Text guildValue;
        // Start is called before the first frame update
        void Start()
        {

        }

        // Update is called once per frame
        void Update()
        {

        }

        void SetUpUI()
        {
            
        }
        public void ExitButton()
        {
            gameObject.SetActive(false);
        }
    }
}

